import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ReactNode } from 'react'
import { cookies } from 'next/headers'
import { Theme } from '~/features/dark-theme/types'
import { BottomNavbar } from '~/widgets/bottom-navbar/bottom-navbar'

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
	const theme =
		cookies().get('theme')?.value === 'dark' ? Theme.dark : Theme.light

	return (
		<html lang='en' className={theme} style={{ colorScheme: theme }}>
			<body className={roboto.className}>
				{children}
				<BottomNavbar />
			</body>
		</html>
	)
}
